### ISSUE TITLE
Web Worker

### ISSUE THREAD

**Issue by matthewp** [skatejs/dom-diff#113]
I'm trying to get this to work in a web worker (diffing 2 trees), ran into a few issues. Happy to send a PR as I get it all worked out.

There's a few of these in the build: https://github.com/skatejs/dom-diff/blob/master/dist/index.js#L301

If we use `self` instead of `window` it will work in both contexts.

Second thing are several `instanceof Node` checks, and since Node is going to be undefined these will throw. Should change those to check if Node is truthy first.

**Comment by treshugart** [comment]
Theres 3 things IIRC:

1. Remove any DOM references in the diffing algorithm
2. Map ids to DOM nodes in the patch instructions instead of passing the node itself as data

**Comment by matthewp** [comment]
Yeah, (2) is what blocked me. In a previous project I had ids that were paths to find the Nodes, like "1.1.3.4.5", I believe React uses (used?) a system like this as well.

**Comment by treshugart** [comment]
> I believe React uses (used?) a system like this as well.

Not sure. I know they have react ids associated to DOM nodes, but I think that's something different.

The difficult is ensuring there's no memory leaks. You could use a `WeakMap`, but then there's GC overhead.
